name: Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.CI_TF_TOKEN }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        env:
          AWS_DEFAULT_REGION: us-west-2
        id: validate
        run: terraform validate -no-color

  bump-version:
    needs: check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

  slack-notification:
    runs-on: ubuntu-latest
    needs: check
    if: always() && github.event_name == 'push'
    steps:
      - id: update-status
        run: |
          if [ "$STATUS" == "skipped" ]
          then
            echo "::set-output name=status::success"
          else
            echo "::set-output name=status::$STATUS"
          fi
        env:
          STATUS: ${{ needs.check.result }}

      - name: Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ steps.update-status.outputs.status }}
          fields: repo,message,commit,author,workflow
          channel: '#announce-build'
          if_mention: failure
          mention: 'here'
          text: '${{ github.repository }}:${{ needs.check.outputs.tag }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
